[versions]
gradlePluginPublish = "2.0.0"
licensePlugin = "0.16.1"
junit = "5.14.2"
spock = "2.4-groovy-3.0"

[libraries]
junit-bom = {module = "org.junit:junit-bom", version.ref = "junit" }
junit-platformSuiteEngine = { module = "org.junit.platform:junit-platform-suite-engine" }
junit-platformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
spock-bom = { module = "org.spockframework:spock-bom", version.ref = "spock" }
spock-core = { module = "org.spockframework:spock-core" }

[bundles]

[plugins]
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradlePluginPublish" }
license = { id = "com.github.hierynomus.license", version.ref = "licensePlugin" }
